### ISSUE TITLE
respawn to deathmatch

### ISSUE THREAD

**Issue by Dev-Kevo** [ImagicalGamer/SurvivalGamesV3#114]
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.
- [x] This issue is for SurvivalGamesV3, and not any other plugin.
- [x] This is not a suggestion, but an actual issue NOTE: If it is a suggestion, title it [SUGGESTION] ______

XX = required

clearsky

when time hits 0 for respawn to deathmatch 
it teleports you to the spawn of the map not the deathmatch point

no errors

no errors

**Comment by remotevase** [comment]
??? @Taki21 any ideas? Also, next time, please check the checkboxes

**Comment by ImagicalGamer** [comment]
I think I have a fix.

**Comment by Dev-Kevo** [comment]
Idk dont know how to use the check box sorry

**Comment by remotevase** [comment]
just click on tge box once the issue is submitted

**Comment by Dev-Kevo** [comment]
Tge?

**Comment by remotevase** [comment]
mean "the" XD

**Comment by Dev-Kevo** [comment]
Lol oh that simple wow

**Comment by EpicSteve33** [comment]
I had this same issue on ImagicalMine I thought it was just my server but I guess not lel

**Comment by ImagicalGamer** [comment]
It's the plugin. it doesn't show that it saves the deathmatch. the code shows that it teleports you to the world spawn. Just set the world spawn at your deathmatch arena xD.

**Comment by Dev-Kevo** [comment]
Lol ik i was just think that

**Comment by Driesboy** [comment]
reset your world spawn

**Comment by kaitododoyt** [comment]
Devs, you can add the extra spawn in config, this is very easy, then you can teleport at this spawn instead of world spawn. I can make this if you like, sorry my eng

**Comment by remotevase** [comment]
geez, guys! learn how to appropriately tag these!

**Comment by Taki21** [comment]
Sorry We Dont...LOL

**Comment by Driesboy** [comment]
see my pr

**Comment by remotevase** [comment]
We won't see your PR because, once again, it is not tested.

**Comment by EpicSteve33** [comment]
@remotevase I will test his code when I get home and I will also start helping with BB today after school

**Comment by ImagicalGamer** [comment]
DeathMatch fixed issue closed.
