### ISSUE TITLE
Quit Event

### ISSUE THREAD

**Issue by EpicSteve33** [ImagicalGamer/SurvivalGamesV3#128]
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [ ] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.
- [x] This issue is for SurvivalGamesV3, and not any other plugin.
- [x] This is not a suggestion, but an actual issue NOTE: If it is a suggestion, title it [SUGGESTION] ______

So if a player leaves the match by logging out or if they die and leave the plugin still thinks they are in a match and nobody wins if the counter hits 0 it's kinda annoying, I think to fix this we need to add a quit event. This issue also happens when a player doesn't respawn

**Comment by remotevase** [comment]
Really? That is very strange. I'll work on that soon. Wow, I'm building up quite a list of projects for myself to work on XD

**Comment by EpicSteve33** [comment]
Lel

**Comment by EpicSteve33** [comment]
I would provide video of the bug but I'm not home

**Comment by Driesboy** [comment]
ok i am trying to fix this

**Comment by Driesboy** [comment]
https://github.com/ImagicalGamer/SurvivalGamesV3/pull/132

**Comment by Driesboy** [comment]
Is this fixed now?

**Comment by EpicSteve33** [comment]
I believe so, but I never tested it
