### ISSUE TITLE
Sign Error! (reagain)

### ISSUE THREAD

**Issue by NikeboyHU** [ImagicalGamer/SurvivalGamesV3#141]
DO NOT DELETE THIS!!!!!

Before you make an issue, make sure your issue matches the criteria below
Once the issue is submitted, PLEASE TICK THE CHECKBOXES BY CLICKING ON THEM! 
- [ ] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [ ] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.
- [x] This issue is for SurvivalGamesV3, and not any other plugin.
- [x] This is not a suggestion, but an actual issue NOTE: If it is a suggestion, title it [SUGGESTION] ______

If all the checkboxes are checked, congratulations! Fill out the fields below
* = required

* Please state the server provider below (EG: PocketMine, ImagicalMine, Genysis etc):

* Please state the issue below:

Are there any errors in the console? If so, state them below:

Are there any crash dumps? If so, please paste it below (Paste the entire crash dump, not just the part that it tells you to):

Sign bug: The signs can not connect to the arena again, when player(s) touch this, should fix the problem !

**Comment by remotevase** [comment]
> Please state the server provider below (EG: PocketMine, ImagicalMine, Genysis etc):
> 
> Please state the issue below:

Fill these out please

**Comment by NikeboyHU** [comment]
On VPS, Ubuntu OS, ImagicalMine (1.4 Elite-Dev) phar file. v3.0.6 is working sign normal, and function complete always (laggy problem next bug), but now newer version not working.

**Comment by remotevase** [comment]
Hmmm... @ImagicalGamer @Taki21 could it be a problem with the quit event not working?

**Comment by remotevase** [comment]
Guys, figure out what the labels mean!!!!!!

**Comment by ImagicalGamer** [comment]
lmao I do that just to piss you off sometimes. I don't clearly see the issue here, please explain it.

**Comment by Taki21** [comment]
Ya gotta deal with em : )

**Comment by NikeboyHU** [comment]
Yes, Critical Bug(s)... #140 issue is strongest problem, BUT that is NOT VPS-OS/OS bug. Please try fix problem(s).

**Comment by Taki21** [comment]
#140 is a Server Memory Issue

**Comment by ImagicalGamer** [comment]
Can you please give us the host that you bought your VPS from. And the specs.

**Comment by NikeboyHU** [comment]
VPS bought from host: Infinity Hosting Ltd.
VPS info: 
- OS: Ubuntu Linux 16.04 LTS
- MultiCraft Server Manager (2+1 servers [+1 that is Survival Games server now])
- 3.2 GhZ x64 VCPU
- 4 GB RAM
- 15 GB SSD
- Total Virtual RAM: 4 GB

**Comment by remotevase** [comment]
None of those apply. Im leaving the funny labels, though
