### ISSUE TITLE
If you create sign it say running

### ISSUE THREAD

**Issue by Driesboy** [ImagicalGamer/SurvivalGamesV3#152]
DO NOT DELETE THIS!!!!!

Before you make an issue, make sure your issue matches the criteria below
Once the issue is submitted, PLEASE TICK THE CHECKBOXES BY CLICKING ON THEM! 
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is written in your native language for maximal clarity
- [x] This issue does not have abbreveations. Abbreviations make it not understandable.
- [x] This issue is for SurvivalGamesV3, and not any other plugin.
- [x] This is not a suggestion, but an actual issue <br> <br>

NOTE: If it is a suggestion, title it [SUGGESTION] ______

If all the checkboxes are checked, congratulations! Fill out the fields below
! = required

! <--STATE SERVER PROVIDER HERE (EG POCKETMINE, IMAGICALMINE, GENYSIS etc)-->
Genisys

! <--STATE ISSUE HERE-->
if you create a sign after creating arena it show running and if you restart same

<--PUT ANY CONSOLE ERRORS HERE-->

<--IF CRASH DUMPS ARE AVAILABLE, PASTE THE ENTIRE FILE'S CONTENTS HERE-->

**Comment by remotevase** [comment]
@Driesboy compare the sign creating code between master and Genysis. You're the Genysis manager, after all!

**Comment by Driesboy** [comment]
I use the master!
Op 22-mei-2016 19:23 schreef "remotevase" <notifications@github.com>:

**Comment by remotevase** [comment]
latest build? really?

**Comment by remotevase** [comment]
screenshot plz

**Comment by Driesboy** [comment]
Yes
Op 22-mei-2016 20:05 schreef "remotevase" <notifications@github.com>:

**Comment by Driesboy** [comment]
Ok
Op 22-mei-2016 20:06 schreef "remotevase" <notifications@github.com>:

**Comment by Driesboy** [comment]
![image](https://cloud.githubusercontent.com/assets/15795262/15455683/21300838-205c-11e6-81c2-d5d9f5f48dc1.png)

**Comment by Mike4l6** [comment]
You have to set up the sg map again -_-

**Comment by remotevase** [comment]
You have to delete the previous configs

**Comment by Driesboy** [comment]
already done

**Comment by remotevase** [comment]
oh, I see the bug now. I am working on a fix

**Comment by remotevase** [comment]
fixed in master branch for non-genysis
https://github.com/ImagicalGamer/SurvivalGamesV3/releases/tag/3.x
