### ISSUE TITLE
Critical Error

### ISSUE THREAD

**Issue by Mike4l6** [ImagicalGamer/SurvivalGamesV3#159]
DO NOT DELETE THIS!!!!!

Before you make an issue, make sure your issue matches the criteria below
Once the issue is submitted, PLEASE TICK THE CHECKBOXES BY CLICKING ON THEM! 
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is written in your native language for maximal clarity
- [x] This issue does not have abbreveations. Abbreviations make it not understandable.
- [x] This issue is for SurvivalGamesV3, and not any other plugin.
- [x] This is not a suggestion, but an actual issue<br> <br>

NOTE: If it is a suggestion, title it [SUGGESTION] ______

If all the checkboxes are checked, congratulations! Fill out the fields below
! = required

! <--STATE SERVER PROVIDER HERE (EG POCKETMINE, IMAGICALMINE, GENYSIS etc)-->

! <--STATE ISSUE HERE--> I do not know how this occurs it keeps repeating

<--PUT ANY CONSOLE ERRORS HERE--> [13:06:15] critical> Could not execute task SurvivalGamesV3\GameSender: Call to a member function clearAll() on null
[13:06:15] critical> Error: "Call to a member function clearAll() on null" (EXCEPTION) in "/SurvivalGamesV3DMFix.phar/src/SurvivalGamesV3/SurvivalGamesV3" at line 795

<--IF CRASH DUMPS ARE AVAILABLE, PASTE THE ENTIRE FILE'S CONTENTS HERE-->

**Comment by remotevase** [comment]
I'll take a look

**Comment by remotevase** [comment]
I will fix soon. Does it crash the server? I'll fix it in 1 or 2 days
